
package scrabbleedd;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdom2.*;
import org.jdom2.input.SAXBuilder;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;

/**
 *
 * @author KMMG
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    File archivo;
    JFileChooser fc;
    String path;
    public String dimension;

    public Diccionario d;
    public Dobles db;
    public Triples tr;
    
    public Inicio() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        archivo = null;
        fc = null;
        path="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Iniciar Juego");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        fc =new JFileChooser();
        FileNameExtensionFilter filtro =new FileNameExtensionFilter("XML Files","xml");
        fc.setFileFilter(filtro);
 
        
        int seleccion=fc.showOpenDialog(null);
 
        
        if(seleccion==JFileChooser.APPROVE_OPTION){

            archivo =fc.getSelectedFile();
            System.out.println("Entró al path: "+archivo.getAbsolutePath());
            cargarXml(archivo.getAbsolutePath());
            jButton2.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cargarXml(String pathfile){
        
        d = new Diccionario();
        db = new Dobles();
        tr = new Triples();
        //Se crea un SAXBuilder para poder parsear el archivo
        SAXBuilder builder = new SAXBuilder();
        File xmlFile = new File( pathfile );
        try
        {
            Document document = (Document) builder.build(xmlFile);
            Element rootNode = document.getRootElement();
            String valorDimension = rootNode.getChildText("dimension");
            System.out.println("Dimension : " + valorDimension);
            
            List list_db = rootNode.getChildren("dobles");
            for(int i = 0; i<list_db.size();i++){
                Element doble = (Element)list_db.get(i);
                
                List casillas = doble.getChildren();
                for(int j = 0; j<casillas.size();j++){
                    Element casilla = (Element)casillas.get( j );
                    System.out.println("Doble->");
                    System.out.println("Pos X: " + casilla.getChildText("x"));
                    System.out.println("Pos Y: " + casilla.getChildText("y"));
                    System.out.println();
                    int x= Integer.parseInt(casilla.getChildText("x"));
                    int y= Integer.parseInt(casilla.getChildText("y"));
                    db.agregar(x, y);
                }
            }
            
            
            List list_tr = rootNode.getChildren("triples");
            for(int i = 0; i<list_tr.size();i++){
                Element triple = (Element)list_tr.get(i);
                
                List casillas = triple.getChildren();
                for(int j = 0; j<casillas.size();j++){
                    Element casilla = (Element)casillas.get( j );
                    System.out.println("Triple->");
                    System.out.println("Pos X: " + casilla.getChildText("x"));
                    System.out.println("Pos Y: " + casilla.getChildText("y"));
                    System.out.println();
                    int x= Integer.parseInt(casilla.getChildText("x"));
                    int y= Integer.parseInt(casilla.getChildText("y"));
                    tr.agregar(x, y);
                    
                }
            }
            
            Element dic = rootNode.getChild("diccionario");
            List words = dic.getChildren("palabra");
            for(int i = 0; i<words.size();i++){
                Element word = (Element)words.get(i);
                System.out.println("Palabra: " + word.getText());
                d.agregar(word.getText());
                
            }
            
            
        }catch ( IOException io ) {
            System.out.println( io.getMessage() );
        }catch ( JDOMException jdomex ) {
            System.out.println( jdomex.getMessage() );
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        RegistroJugadores rj = new RegistroJugadores(db,tr,d,dimension);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
